sonar.projectKey=Fineconia
sonar.projectName=Fineconia
sonar.projectVersion=1.0

# Archivos a analizar
sonar.sources=.

# Ignorar carpetas
sonar.exclusions=vendor/**, storage/**, node_modules/**

# Servidor SonarQube
sonar.host.url=http://localhost:9000

# Token de acceso
sonar.login=sqa_4418dc4e67a8a7d6e7b3c417e22257dd9ed78aba

# Codificación
sonar.sourceEncoding=UTF-8